language: objective-c
osx_image: xcode7
xcode_project: MKImpulseDemo/MKImpulseManagerDemo.xcodeproj
xcode_scheme: MKImpulseManagerDemo

script:
- xctool -project MKImpulseDemo/MKImpulseManagerDemo.xcodeproj -scheme MKImpulseManagerDemo build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO